-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.activity_log
(
    id serial NOT NULL,
    user_id integer,
    user_email character varying(100) COLLATE pg_catalog."default",
    action character varying(100) COLLATE pg_catalog."default",
    details text COLLATE pg_catalog."default",
    ip_address character varying(45) COLLATE pg_catalog."default",
    "timestamp" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT activity_log_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.course_cohorts
(
    id serial NOT NULL,
    course_id integer,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    start_date date NOT NULL,
    end_date date NOT NULL,
    max_attendees integer DEFAULT 20,
    status character varying(20) COLLATE pg_catalog."default" DEFAULT 'published'::character varying,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT course_cohorts_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.courses
(
    id serial NOT NULL,
    title character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    content text COLLATE pg_catalog."default",
    duration integer,
    category character varying(100) COLLATE pg_catalog."default",
    status character varying(20) COLLATE pg_catalog."default" DEFAULT 'draft'::character varying,
    instructor_id integer,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    required_hours numeric(5, 2) DEFAULT 3.00,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    is_locked boolean DEFAULT false,
    duration_minutes integer DEFAULT 60,
    CONSTRAINT courses_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.lessons
(
    id serial NOT NULL,
    course_id integer,
    title character varying(255) COLLATE pg_catalog."default" NOT NULL,
    content text COLLATE pg_catalog."default" NOT NULL,
    order_index integer DEFAULT 0,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT lessons_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.password_resets
(
    id serial NOT NULL,
    user_id integer NOT NULL,
    token character varying(255) COLLATE pg_catalog."default" NOT NULL,
    expires_at timestamp without time zone NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT password_resets_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.question_options
(
    id serial NOT NULL,
    question_id integer,
    option_text text COLLATE pg_catalog."default" NOT NULL,
    is_correct boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT question_options_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.questions
(
    id serial NOT NULL,
    course_id integer,
    lesson_id integer,
    question_text text COLLATE pg_catalog."default" NOT NULL,
    question_type character varying(50) COLLATE pg_catalog."default" DEFAULT 'multiple_choice'::character varying,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT questions_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.system_settings
(
    setting_key character varying(100) COLLATE pg_catalog."default" NOT NULL,
    setting_value text COLLATE pg_catalog."default" NOT NULL,
    description character varying(255) COLLATE pg_catalog."default",
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT system_settings_pkey PRIMARY KEY (setting_key)
);

CREATE TABLE IF NOT EXISTS public.user_attachments
(
    id serial NOT NULL,
    user_id integer,
    file_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    file_path text COLLATE pg_catalog."default" NOT NULL,
    file_type character varying(50) COLLATE pg_catalog."default",
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT user_attachments_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.user_course_progress
(
    id serial NOT NULL,
    user_id integer,
    course_id integer,
    status character varying(20) COLLATE pg_catalog."default" DEFAULT 'not_started'::character varying,
    enrolled_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    completion_date timestamp with time zone,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    hours_completed numeric(5, 2) DEFAULT 0.00,
    last_accessed_lesson_id integer,
    score integer DEFAULT 0,
    cohort_id integer,
    CONSTRAINT user_course_progress_pkey PRIMARY KEY (id),
    CONSTRAINT user_course_progress_user_id_cohort_id_key UNIQUE (user_id, cohort_id)
);

CREATE TABLE IF NOT EXISTS public.user_lesson_progress
(
    id serial NOT NULL,
    user_id integer,
    lesson_id integer NOT NULL,
    status character varying(20) COLLATE pg_catalog."default" DEFAULT 'not_started'::character varying,
    completion_date timestamp with time zone,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT user_lesson_progress_pkey PRIMARY KEY (id),
    CONSTRAINT user_lesson_progress_user_id_lesson_id_key UNIQUE (user_id, lesson_id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id serial NOT NULL,
    first_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    email character varying(100) COLLATE pg_catalog."default" NOT NULL,
    password text COLLATE pg_catalog."default" NOT NULL,
    job_title character varying(100) COLLATE pg_catalog."default",
    access_level character varying(20) COLLATE pg_catalog."default" DEFAULT 'user'::character varying,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    failed_login_attempts integer DEFAULT 0,
    lockout_until timestamp with time zone,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_email_key UNIQUE (email)
);

ALTER TABLE IF EXISTS public.course_cohorts
    ADD CONSTRAINT course_cohorts_course_id_fkey FOREIGN KEY (course_id)
    REFERENCES public.courses (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.courses
    ADD CONSTRAINT courses_instructor_id_fkey FOREIGN KEY (instructor_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.lessons
    ADD CONSTRAINT lessons_course_id_fkey FOREIGN KEY (course_id)
    REFERENCES public.courses (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_lessons_course
    ON public.lessons(course_id);


ALTER TABLE IF EXISTS public.password_resets
    ADD CONSTRAINT password_resets_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.question_options
    ADD CONSTRAINT question_options_question_id_fkey FOREIGN KEY (question_id)
    REFERENCES public.questions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.questions
    ADD CONSTRAINT questions_course_id_fkey FOREIGN KEY (course_id)
    REFERENCES public.courses (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.questions
    ADD CONSTRAINT questions_lesson_id_fkey FOREIGN KEY (lesson_id)
    REFERENCES public.lessons (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.user_attachments
    ADD CONSTRAINT user_attachments_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_attachments_user
    ON public.user_attachments(user_id);


ALTER TABLE IF EXISTS public.user_course_progress
    ADD CONSTRAINT fk_ucp_last_lesson FOREIGN KEY (last_accessed_lesson_id)
    REFERENCES public.lessons (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_ucp_last_lesson
    ON public.user_course_progress(last_accessed_lesson_id);


ALTER TABLE IF EXISTS public.user_course_progress
    ADD CONSTRAINT user_course_progress_cohort_id_fkey FOREIGN KEY (cohort_id)
    REFERENCES public.course_cohorts (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.user_course_progress
    ADD CONSTRAINT user_course_progress_course_id_fkey FOREIGN KEY (course_id)
    REFERENCES public.courses (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_ucp_course
    ON public.user_course_progress(course_id);


ALTER TABLE IF EXISTS public.user_course_progress
    ADD CONSTRAINT user_course_progress_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.user_lesson_progress
    ADD CONSTRAINT user_lesson_progress_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

END;